import fs from "fs";
import path from "path";

// openapi.json is generated by: npm run generate-docs
// It lives at functions/openapi.json, which resolves to:
//   - dev (ts-node):  __dirname = functions/src/config  → ../../openapi.json
//   - prod (compiled): __dirname = functions/lib/config → ../../openapi.json
const openApiPath = path.join(__dirname, "../../openapi.json");

export const swaggerSpec = fs.existsSync(openApiPath)
  ? JSON.parse(fs.readFileSync(openApiPath, "utf-8"))
  : { openapi: "3.0.0", info: { title: "Alegria API", version: "1.0.0" }, paths: {} };
